### ISSUE TITLE
Never use try catch in Program.cs

### ISSUE THREAD

**Issue by AbhiDashadiya** [namraravani/HRMS-Project#10]
![image](https://github.com/user-attachments/assets/dd072215-d193-460a-b251-4922411779d5)

**Comment by namraravani** [comment]
Solved the issue related to Try Catch block was used in program.cs file 
earlier I used that for testing purpose forgot to remove it 

![image](https://github.com/user-attachments/assets/61de276f-8362-4ca7-bd8f-650993b16012)



> ![image](https://private-user-images.githubusercontent.com/109543748/372578879-dd072215-d193-460a-b251-4922411779d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDUzOTksIm5iZiI6MTcyNzg0NTA5OSwicGF0aCI6Ii8xMDk1NDM3NDgvMzcyNTc4ODc5LWRkMDcyMjE1LWQxOTMtNDYwYS1iMjUxLTQ5MjI0MTE3NzlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNDU4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDc5MjhhMzYxOTAyNzc5NDNjN2YxYmFhMmIwZTZlZTYyZTQ5ZjM2ZmZjYjNkZThmNjYxYjk2ZjdiYmYxMTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zLDPc-lbs-lqRCiol26JKq-CiOTbdFMI0JDoUhVtyxk)
