### ISSUE TITLE
Direct use of Dbcontext in controller

### ISSUE THREAD

**Issue by AbhiDashadiya** [namraravani/HRMS-Project#2]
you never inject the dbcontext in controller it only used in the repository part 

![image](https://github.com/user-attachments/assets/d44ea790-58b3-4d1f-809d-e4c2e4783940)

**Comment by namraravani** [comment]
Removed the unused dependency of DbContext from controller first when I wasn't using the repository pattern I used it but now when I am using the repository method I don't need it here 
![image](https://github.com/user-attachments/assets/997f8672-5667-4519-b337-e1a8e589de27)

Please Review it 


> you never inject the dbcontext in controller it only used in the repository part
> 
> ![image](https://private-user-images.githubusercontent.com/109543748/372493607-d44ea790-58b3-4d1f-809d-e4c2e4783940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDYwNTQsIm5iZiI6MTcyNzg0NTc1NCwicGF0aCI6Ii8xMDk1NDM3NDgvMzcyNDkzNjA3LWQ0NGVhNzkwLTU4YjMtNGQxZi04MDlkLWU0YzJlNDc4Mzk0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNTA5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGZhNDMyY2JlYTk5ZjUxMWE1OGU0OWIxNWQzMjhhOGNkZWVlMzI4NWE5YmRhOWE5OTNkYmIzOTNiOWUyOTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zkEPayqjBtfFwPHPodBE8tD43rnNMmzlYSH4X8avO-E)
