### ISSUE TITLE
Need to be proper file folder structure

### ISSUE THREAD

**Issue by AbhiDashadiya** [namraravani/HRMS-Project#4]
context need to be in Data or other related name

![image](https://github.com/user-attachments/assets/c56d522c-a4b2-41b3-8474-3ea845801064)

**Comment by AbhiDashadiya** [comment]
DTO folder and Model folder should be different not inside each other


![image](https://github.com/user-attachments/assets/391631f7-c9fa-4476-ba85-bd624652d986)

**Comment by namraravani** [comment]
Here is the changes made according to the issue that has been generated by you  

![image](https://github.com/user-attachments/assets/59a3a1df-7f2c-40f2-b12b-81fce5ee41d8)


> context need to be in Data or other related name
> 
> ![image](https://private-user-images.githubusercontent.com/109543748/372497104-c56d522c-a4b2-41b3-8474-3ea845801064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDMxMDgsIm5iZiI6MTcyNzg0MjgwOCwicGF0aCI6Ii8xMDk1NDM3NDgvMzcyNDk3MTA0LWM1NmQ1MjJjLWE0YjItNDFiMy04NDc0LTNlYTg0NTgwMTA2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNDIwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2Y4MDNkY2IxNzE5YjA4MzdmYzI1Yzc3NGMyNzlmNmFkOTI1NTE3Y2M5NGUxOGJjMjFlMWQ5Y2JkY2VkZThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wNAf6iZueMEwFBK4E6PI6AGStZaTEQj7fOy8Ur_xqB4)

**Comment by namraravani** [comment]
Fixed the other issue related to the folder structure of the DTO folder

**Comment by namraravani** [comment]
Fixed the other issue related to folder structure of the DTO folder
![image](https://github.com/user-attachments/assets/0b14dc79-47d2-42da-8373-7d12e386c7cb)


> DTO folder and Model folder should be different not inside each other
> 
> ![image](https://private-user-images.githubusercontent.com/109543748/372502934-391631f7-c9fa-4476-ba85-bd624652d986.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDMxMDgsIm5iZiI6MTcyNzg0MjgwOCwicGF0aCI6Ii8xMDk1NDM3NDgvMzcyNTAyOTM0LTM5MTYzMWY3LWM5ZmEtNDQ3Ni1iYTg1LWJkNjI0NjUyZDk4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNDIwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzFiMmY3MTU3MGQ4ZGIyYTNlMjZhNzBkOTc5ZWM5N2I5NGRkNDRlYWFlNTdlNGFkZjg2MmI1Nzg0NGM4MDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GMKHv95BSk-3rNmBpLvOaR5MlzSawgGOEpTR1OhuD70)
