### ISSUE TITLE
No need to specify the Public keyword in Interface

### ISSUE THREAD

**Issue by AbhiDashadiya** [namraravani/HRMS-Project#6]
![image](https://github.com/user-attachments/assets/c5a54820-45a0-47c4-8350-a81ddf6d0b6f)

**Comment by namraravani** [comment]
Solved the issue related to the public keyword was used in the interface in all the repository

![image](https://github.com/user-attachments/assets/541e289f-3fca-48b2-b060-bfbafac8211b)


> ![image](https://private-user-images.githubusercontent.com/109543748/372571750-c5a54820-45a0-47c4-8350-a81ddf6d0b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDQ1MzcsIm5iZiI6MTcyNzg0NDIzNywicGF0aCI6Ii8xMDk1NDM3NDgvMzcyNTcxNzUwLWM1YTU0ODIwLTQ1YTAtNDdjNC04MzUwLWE4MWRkZjZkMGI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNDQzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDg1MzViMWMzNGU3M2Q1N2RjMzg2ODgxZTYwYTY4NDAxMmZkN2M2YWQyZWM4MzY0M2MyNGQyMmI3NmY0YzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ET-P2X9xbWVv9-yZR-mDhKvBaJVb38yJVYxAF07Q5cg)
